### ISSUE TITLE
Question auth

### ISSUE THREAD

**Issue by alan345** [dassiorleando/gistology#1]
Hi!
Great stack! Thanks a lot.
What do you recommend for authentication for this stack?
Thanks
Alan

**Comment by dassiorleando** [comment]
Hi @alan345,
You're welcome.

I muchly appreciate **passport** for security, it even has a lot of extensions for social connection.

If you are interested to add it to this starter with me, please let me know we proceed.
Cheers.

**Comment by alan345** [comment]
Ok sure! I will do a pull request if I manage to implement it! 
Thanks
Alan

**Comment by alan345** [comment]
FYI, Before doing that, There are some breaking changes with new version of material. they use CDK and rename it. (e.g MdDialog to MatDialog)

**Comment by dassiorleando** [comment]
@alan345 Ok understood, Thanks so much.
I'll change the dialog component accordingly.

**Comment by alan345** [comment]
Thanks so much

**Comment by alan345** [comment]
I have updated your stack(with new version of angular cli and material). Compilation is good but I have issues. You want a pull request of this 'partial work' ?

**Comment by dassiorleando** [comment]
@alan345 it's all good, cool.
Please make a pull request on a **new branch** I'll accept it, then we'll continue to review it together if you don't mind and merge later on **master**.

**Comment by alan345** [comment]
hello!
I have done the PR: https://github.com/dassiorleando/gistology/pull/2
Thanks

**Comment by alan345** [comment]
Cool! here you have some designs bugs:

![image](https://user-images.githubusercontent.com/15246526/31636867-10738c96-b281-11e7-82ea-61734318ae78.png)

**Comment by dassiorleando** [comment]
@alan345 it breaks the original design of the starter, I just merge it into the develop branch for the moment once it's Ok we merge with the master branch.

**Comment by dassiorleando** [comment]
Please, how fare here @alan345 ?

**Comment by dassiorleando** [comment]
@alan345 I have finally updated the stack, you can check it out.
All is well as expected.
💯
