### ISSUE TITLE
Version error 

### ISSUE THREAD

**Issue by Dhursh** [dassiorleando/gistology#3]
Hi,
Getting below error,
My current npm and node versions are below,
npm - 5.6.0
node- 8.9.0

Please suggest

ERROR in Metadata version mismatch for module E:/project/gistology-master/gistology-master/node_modules/@angular/flex-layout/typings/index.d.ts, found version 4, expected 3

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'E:\project\gistology-master\gistology-master\src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gistology@0.5.0 postinstall: `ng build --aot -prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gistology@0.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by dassiorleando** [comment]
@Dhursh sorry for late reply, the version of Gistology  you have tried as stated into the package.json was using:
- "node": "6.10.2",
- "npm": "4.5.0"

In the meantime, I have just updated the versions of the starter, now we're using Angular 5, try to test again and let me know.
**Note: Be sure to see the version stated in the package.json**

**Comment by dassiorleando** [comment]
I'll close this thread as for me it's not really a bug.
